openapi: 3.0.0
info:
  title: 온라인 명륜당 API
  version: 0.0.1
  description:
    $ref: ./updates.yaml
servers:
  - url: http://15.165.236.169:3000/api
    description: AWS 주소
  - url: http://localhost:3000/api
    description: localhost 주소

tags:
  $ref: ./tags.yaml

paths: # paths는 무조건 있어야 함
  $ref: ./paths/index.yaml

components: